# Stage 1: Build
FROM node:16.20.2-alpine AS build

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

RUN yarn build

# Stage 2: Production
FROM node:16.20.2-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY package.json .
COPY yarn.lock .
COPY ormconfig.js .

RUN yarn install --production

COPY --from=build /app/dist ./dist

EXPOSE 5000

ENTRYPOINT [ "yarn", "start:prod" ]
